// Code generated by file2byteslice. DO NOT EDIT.

package main

var circle_go = []byte("//go:build ignore\n\npackage main\n\nvar Radius float\nvar Color vec4\n\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\n\talpha := 1.0\n\tcenter := vec2(Radius, Radius)\n\tif distance(texCoord, center) >= Radius {\n\t\talpha = 0.0\n\t}\n\treturn Color * alpha\n}\n")
